clear variables
close all
whichMac = char(java.lang.System.getProperty('user.name'));
savedir = ['/Users/' whichMac '/The University of Nottingham/SPMIC User Groups - Imaging for Neuroscience/Monthly_meetings/meeting_nov24/'];

mypath = '/Users/spmic/data/';


fMRI_gen_file = readtable([mypath 'fMRI.csv']);
fMRI_task_file = readtable([mypath 'taskfMRI.csv']);
fMRI_rs_file = readtable([mypath 'rsfMRI.csv']);
fMRI_uhf_file = readtable([mypath 'uhffmri.csv']);
fMRI_clin_file = readtable([mypath 'clinicalfmri.csv']);
fMRI_conn_file = readtable([mypath 'fMRIconn.csv']);
fMRI_bold_file = readtable([mypath 'boldfmri.csv']);
fMRI_se_file = readtable([mypath 'sefmri.csv']);
fMRI_layer_file = readtable([mypath 'layerfmri.csv']);
fMRI_machlearn_file = readtable([mypath 'mach.csv']);
% fix missing entries in UHF
tmpY = [fMRI_uhf_file.Year(1:26); 1998; fMRI_uhf_file.Year(27:32); 1991; fMRI_uhf_file.Year(33)];
tmpX = [fMRI_uhf_file.Count(1:26); 0; fMRI_uhf_file.Count(27:32); 0; fMRI_uhf_file.Count(33)];

fMRI_uhf_file = table; % clear height issue 

fMRI_uhf_file.Year = tmpY;
fMRI_uhf_file.Count = tmpX;

% fix missing entries in BOLD
tmpY2 = [fMRI_bold_file.Year(1:29); 1995;1994;1993;1992;1991;1990];
tmpX2 = [fMRI_bold_file.Count(1:29); zeros(6,1)];

fMRI_bold_file = table; % clear height issue 

fMRI_bold_file.Year = tmpY2;
fMRI_bold_file.Count = tmpX2;

% fix missing entries in machine learning
tmpY3 = [fMRI_machlearn_file.Year(1:22); 2002;2001;2000;1999;1998;1997;1996;1995; fMRI_machlearn_file.Year(23); 1993;1992;1991;1990 ];
tmpX3 = [fMRI_machlearn_file.Count(1:22); zeros(8,1); fMRI_machlearn_file.Count(23); zeros(4,1) ];

fMRI_machlearn_file = table; % clear height issue 

fMRI_machlearn_file.Year = tmpY3;
fMRI_machlearn_file.Count = tmpX3;
%%
mapCol = [166,206,227;...
31,120,180;...
178,223,138;...
51,160,44;...
251,154,153;...
227,26,28;...
253,191,111;...
255,127,0;...
202,178,214;...
106,61,154];
mapCol = mapCol/256;
%%
x = [fMRI_gen_file.Year; fMRI_gen_file.Year; fMRI_gen_file.Year;...
    fMRI_gen_file.Year; fMRI_gen_file.Year; fMRI_gen_file.Year;...
    fMRI_gen_file.Year; fMRI_gen_file.Year; fMRI_gen_file.Year;...
    fMRI_gen_file.Year];

y = [fMRI_gen_file.Count; fMRI_task_file.Count; fMRI_rs_file.Count;...
    fMRI_uhf_file.Count; fMRI_clin_file.Count; fMRI_conn_file.Count;...
    fMRI_bold_file.Count; fMRI_se_file.Count; fMRI_layer_file.Count;...
    fMRI_machlearn_file.Count];

grp = [repmat({'fMRI'},length(fMRI_gen_file.Year),1);...
    repmat({'task fMRI'},length(fMRI_task_file.Year),1);...
    repmat({'rs fMRI'},length(fMRI_rs_file.Year),1);...
    repmat({'UHF fMRI'},length(fMRI_uhf_file.Year),1);...
    repmat({'Clinical fMRI'},length(fMRI_clin_file.Year),1);...
    repmat({'Connectivity fMRI'},length(fMRI_clin_file.Year),1);...
    repmat({'BOLD fMRI'},length(fMRI_bold_file.Year),1);...
    repmat({'SE fMRI'},length(fMRI_se_file.Year),1);...
    repmat({'Layer fMRI'},length(fMRI_layer_file.Year),1);...
    repmat({'Machine Learning fMRI'},length(fMRI_machlearn_file.Year),1)];
% Plot using Gramm
close all
figure('Position',[100 100 1024 768])
clear g
g = gramm('x', x, 'y', y, 'color', grp);
g.geom_point
g.set_title('PubMed: Number of Publications (Nov 1990-Nov 2024)');
g.set_names('x', 'Year', 'y', 'Publications', 'color', 'Search term');
g.set_text_options('base_size', 14);
g.set_point_options('markers', {'o'} ,'base_size',12)
g.axe_property('XGrid','on','YGrid','on');
g.set_color_options('map',mapCol)
g.set_order_options('color',0)
g.draw();

g.update('y',y)
g.geom_line()
g.no_legend
g.draw()
filename = 'fMRITrends_1';
g.export('file_name',filename, ...
    'export_path',...
    savedir,...
    'file_type','pdf')
g.export('file_name',filename, ...
    'export_path',...
    savedir,...
    'file_type','eps')

%%
x = [fMRI_task_file.Year; fMRI_task_file.Year; fMRI_task_file.Year;...
    fMRI_task_file.Year; fMRI_task_file.Year; fMRI_task_file.Year; ...
    fMRI_task_file.Year; fMRI_task_file.Year];
y = [fMRI_task_file.Count; fMRI_rs_file.Count;...
    fMRI_uhf_file.Count; fMRI_conn_file.Count;...
    fMRI_bold_file.Count; fMRI_se_file.Count;...
    fMRI_layer_file.Count; fMRI_machlearn_file.Count];
grp = [
    repmat({'task fMRI'},length(fMRI_task_file.Year),1);...
    repmat({'rs fMRI'},length(fMRI_rs_file.Year),1);...
    repmat({'UHF fMRI'},length(fMRI_uhf_file.Year),1);...
    repmat({'connectivity fMRI'},length(fMRI_conn_file.Year),1);...
    repmat({'bold fMRI'},length(fMRI_bold_file.Year),1);...
    repmat({'se fMRI'},length(fMRI_se_file.Year),1);...
    repmat({'layer fMRI'},length(fMRI_layer_file.Year),1);...
    repmat({'machine learning fMRI'},length(fMRI_machlearn_file.Year),1);...
    ];


figure('Position',[100 100 1024 768])
clear g
g = gramm('x', x, 'y', y, 'color', grp);
g.geom_point
g.set_title('PubMed: Number of Publications (Nov 1990-Nov 2024)');
g.set_names('x', 'Year', 'y', 'Publications', 'color', 'Search term');
g.set_text_options('base_size', 14);
g.set_point_options('markers', {'o'} ,'base_size',12)
g.axe_property('XGrid','on','YGrid','on');
g.set_color_options('map',mapCol([2,3,4,6,7,8,9,10],:))
g.set_order_options('color',0)
g.draw();

g.update('y',y)
g.geom_line()
g.no_legend
g.draw()

filename = 'fMRITrends_2';
g.export('file_name',filename, ...
    'export_path',...
    savedir,...
    'file_type','pdf')
g.export('file_name',filename, ...
    'export_path',...
    savedir,...
    'file_type','eps')

%% zoom enhance
x = [fMRI_task_file.Year; fMRI_task_file.Year; fMRI_task_file.Year;...
    fMRI_task_file.Year];
y = [
    fMRI_uhf_file.Count;...
    fMRI_bold_file.Count; fMRI_se_file.Count;...
    fMRI_layer_file.Count;];
grp = [
    repmat({'UHF fMRI'},length(fMRI_uhf_file.Year),1);...
    repmat({'bold fMRI'},length(fMRI_bold_file.Year),1);...
    repmat({'se fMRI'},length(fMRI_se_file.Year),1);...
    repmat({'layer fMRI'},length(fMRI_layer_file.Year),1);...
    ];


figure('Position',[100 100 1024 768])
clear g
g = gramm('x', x, 'y', y, 'color', grp);
g.geom_point
g.set_title('PubMed: Number of Publications (Nov 1990-Nov 2024)');
g.set_names('x', 'Year', 'y', 'Publications', 'color', 'Search term');
g.set_text_options('base_size', 14);
g.set_point_options('markers', {'o'} ,'base_size',12)
g.axe_property('XGrid','on','YGrid','on');
g.set_color_options('map',mapCol([4,7,8,9],:))
g.set_order_options('color',0)
g.draw();

g.update('y',y)
g.geom_line()
g.no_legend
g.draw()

filename = 'fMRITrends_3';
g.export('file_name',filename, ...
    'export_path',...
    savedir,...
    'file_type','pdf')
g.export('file_name',filename, ...
    'export_path',...
    savedir,...
    'file_type','eps')
